### ISSUE TITLE
mqtt sketch gives error in compiling

### ISSUE THREAD

**Issue by rajbadri** [armtronix/NodeMCU_four_relay_board#1]
hi i have bought a amtronix 4 channel relay board through tindie and was trying out the arduino sketches.
The mqtt sketch does not compile and gives this error.

Arduino: 1.6.5 (Mac OS X), Board: "Generic ESP8266 Module, Serial, 80 MHz, 40MHz, DIO, 115200, 512K (64K SPIFFS)"

Using library ESP8266WiFi in folder: /Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WiFi 
Using library PubSubClient in folder: /Users/rajbadri/Documents/Arduino/libraries/pubsubclient 

/Users/rajbadri/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9/bin/xtensa-lx106-elf-g++ -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/tools/sdk//include -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -DF_CPU=80000000L -DARDUINO=10605 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DESP8266 -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/cores/esp8266 -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/variants/generic -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WiFi/src -I/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src /var/folders/hg/jblrvjks6tl65wsrsc7fs9c00000gn/T/build4444859270152698191.tmp/amtronics-esp-mqtt.cpp -o /var/folders/hg/jblrvjks6tl65wsrsc7fs9c00000gn/T/build4444859270152698191.tmp/amtronics-esp-mqtt.cpp.o 
amtronics-esp-mqtt.ino:11:15: warning: deprecated conversion from string constant to 'char_' [-Wwrite-strings]
amtronics-esp-mqtt.ino:21:41: error: no matching function for call to 'PubSubClient::PubSubClient(WiFiClient&, IPAddress&, int)'
amtronics-esp-mqtt.ino:21:41: note: candidates are:
In file included from amtronics-esp-mqtt.ino:10:0:
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:99:4: note: PubSubClient::PubSubClient(const char_, uint16_t, void (_)(char_, uint8_t_, unsigned int), Client&, Stream&)
    PubSubClient(const char_, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client, Stream&);
    ^
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:99:4: note:   candidate expects 5 arguments, 3 provided
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:98:4: note: PubSubClient::PubSubClient(const char_, uint16_t, void (_)(char_, uint8_t_, unsigned int), Client&)
    PubSubClient(const char_, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client);
    ^
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:98:4: note:   candidate expects 4 arguments, 3 provided
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:97:4: note: PubSubClient::PubSubClient(const char_, uint16_t, Client&, Stream&)
    PubSubClient(const char_, uint16_t, Client& client, Stream&);
    ^
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:97:4: note:   candidate expects 4 arguments, 3 provided
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:96:4: note: PubSubClient::PubSubClient(const char_, uint16_t, Client&)
    PubSubClient(const char_, uint16_t, Client& client);
    ^
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:96:4: note:   no known conversion for argument 1 from 'WiFiClient' to 'const char_'
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:95:4: note: PubSubClient::PubSubClient(uint8_t_, uint16_t, void (_)(char_, uint8_t_, unsigned int), Client&, Stream&)
    PubSubClient(uint8_t _, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client, Stream&);
    ^
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:95:4: note:   candidate expects 5 arguments, 3 provided
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:94:4: note: PubSubClient::PubSubClient(uint8_t_, uint16_t, void (_)(char_, uint8_t_, unsigned int), Client&)
    PubSubClient(uint8_t *, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client);
    ^
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:94:4: note:   candidate expects 4 arguments, 3 provided
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:93:4: note: PubSubClient::PubSubClient(uint8_t_, uint16_t, Client&, Stream&)
    PubSubClient(uint8_t _, uint16_t, Client& client, Stream&);
    ^
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:93:4: note:   candidate expects 4 arguments, 3 provided
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:92:4: note: PubSubClient::PubSubClient(uint8_t_, uint16_t, Client&)
    PubSubClient(uint8_t _, uint16_t, Client& client);
    ^
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:92:4: note:   no known conversion for argument 1 from 'WiFiClient' to 'uint8_t_ {aka unsigned char_}'
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:91:4: note: PubSubClient::PubSubClient(IPAddress, uint16_t, void (_)(char_, uint8_t_, unsigned int), Client&, Stream&)
    PubSubClient(IPAddress, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client, Stream&);
    ^
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:91:4: note:   candidate expects 5 arguments, 3 provided
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:90:4: note: PubSubClient::PubSubClient(IPAddress, uint16_t, void (_)(char_, uint8_t*, unsigned int), Client&)
    PubSubClient(IPAddress, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client);
    ^
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:90:4: note:   candidate expects 4 arguments, 3 provided
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:89:4: note: PubSubClient::PubSubClient(IPAddress, uint16_t, Client&, Stream&)
    PubSubClient(IPAddress, uint16_t, Client& client, Stream&);
    ^
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:89:4: note:   candidate expects 4 arguments, 3 provided
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:88:4: note: PubSubClient::PubSubClient(IPAddress, uint16_t, Client&)
    PubSubClient(IPAddress, uint16_t, Client& client);
    ^
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:88:4: note:   no known conversion for argument 1 from 'WiFiClient' to 'IPAddress'
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:87:4: note: PubSubClient::PubSubClient(Client&)
    PubSubClient(Client& client);
    ^
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:87:4: note:   candidate expects 1 argument, 3 provided
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:86:4: note: PubSubClient::PubSubClient()
    PubSubClient();
    ^
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:86:4: note:   candidate expects 0 arguments, 3 provided
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:67:7: note: constexpr PubSubClient::PubSubClient(const PubSubClient&)
 class PubSubClient {
       ^
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:67:7: note:   candidate expects 1 argument, 3 provided
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:67:7: note: constexpr PubSubClient::PubSubClient(PubSubClient&&)
/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src/PubSubClient.h:67:7: note:   candidate expects 1 argument, 3 provided
amtronics-esp-mqtt.ino:30:21: error: 'MQTT' does not name a type
amtronics-esp-mqtt.ino:30:34: error: expected unqualified-id before '&' token
amtronics-esp-mqtt.ino:30:34: error: expected ')' before '&' token
amtronics-esp-mqtt.ino:30:36: error: expected initializer before 'pub'
no matching function for call to 'PubSubClient::PubSubClient(WiFiClient&, IPAddress&, int)'

i am using the pubs client from your github link

Thanks
Raj

**Comment by armtronix** [comment]
I have sent some files to your mail id try it

**Comment by Ankur1Ahuja** [comment]
Hi, 

I am facing the same issue, can you please share the same files with me as well ?

**Comment by armtronix** [comment]
Plz lelect node mcu 0.9 as the board . also if you have any other query plz email is directly
