### ISSUE TITLE
Port problems with 4 relay Wifi board

### ISSUE THREAD

**Issue by Ankur1Ahuja** [armtronix/NodeMCU_four_relay_board#2]
I am trying to compile the WifiWebServer code using Arduino but it is not compiling, but giving an error saying "cannot access COM1". Please suggest what to do.

**Comment by armtronix** [comment]
Plz install ch340 USB to UART driver for Windows , make sure you are connecting it t other correct uaet port ( chk device manager for com port number )also make sure that you have integrated esp boards on  your arduino ide
