### ISSUE TITLE
Repo is not what's on shipped devices?

### ISSUE THREAD

**Issue by RocketPop** [armtronix/NodeMCU_four_relay_board#4]
I was looking through the code to update it - and I think this repo does not have the code that was shipped in the "live" device I got from your Kickstarter. 
For example - on the bottom of my /gpio page there is a "Reboot" command that is in the virtual switch folder, but not in the 4 relay board one.
The code to create a hostname does not match what is actually broadcast. The macToStr appears to separate the host portion with "-", but my registered hostname is separated with "_" and not separated by ":" - it generates "http://esp_c3f9ab/" not "armtronix-c3-f9-ab"
Can you please check for whatever changes you have from the live device? I want to make sure I'm not missing any fixes, etc!   :)

**Comment by armtronix** [comment]
Updated it .Thx for informing
